@startuml
set separator none
title Deployment - Live

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Deployment>
!include <awslib/AWSCommon>
!include <awslib/Storage/SimpleStorageServiceBucket>
!include theme/oracle.puml

AddElementTag("S3 Bucket", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#000000", $sprite="SimpleStorageServiceBucket", $shadowing="", $borderStyle="solid")
AddElementTag("Element", $bgColor="#ffffff", $borderColor="#888888", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="solid")
AddElementTag("Container,Database", $bgColor="#006daa", $borderColor="#004c76", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="solid")
AddElementTag("Athena", $bgColor="#dddddd", $borderColor="#8c4fff", $fontColor="#000000", $sprite="img:https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Analytics/Athena.png{scale=0.46875}", $shadowing="", $borderStyle="solid")
AddElementTag("Container", $bgColor="#006daa", $borderColor="#004c76", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="solid")
AddElementTag("Oracle", $bgColor="#ffffff", $borderColor="#888888", $fontColor="#000000", $sprite="oracle", $shadowing="", $borderStyle="solid")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

Deployment_Node(Live.AmazonWebServices, "Amazon Web Services", $type="", $descr="", $tags="Element", $link="") {
  Deployment_Node(Live.AmazonWebServices.USEast1, "US-East-1", $type="", $descr="", $tags="Element", $link="") {
    Deployment_Node(Live.AmazonWebServices.USEast1.Route53, "Route 53", $type="", $descr="Highly available and scalable cloud DNS service.", $tags="Element", $link="")
    Deployment_Node(Live.AmazonWebServices.USEast1.s3mybucket, "s3://my-bucket", $type="", $descr="", $tags="S3 Bucket", $link="")
    Deployment_Node(Live.AmazonWebServices.USEast1.Athena1, "Athena 1", $type="", $descr="", $tags="Athena", $link="")
    Deployment_Node(Live.AmazonWebServices.USEast1.ElasticLoadBalancer, "Elastic Load Balancer", $type="", $descr="Automatically distributes incoming application traffic.", $tags="Element", $link="")
    WithoutPropertyHeader()
    AddProperty("max","10")
    AddProperty("min","1")
    AddProperty("subnet","10.123.234.0")
    Deployment_Node(Live.AmazonWebServices.USEast1.Autoscalinggroup, "Autoscaling group", $type="", $descr="", $tags="Element", $link="") {
      Deployment_Node(Live.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2, "Amazon EC2", $type="", $descr="", $tags="Element", $link="") {
        Container(Live.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2.WebApplication_1, "Web Application", $techn="Java and Spring Boot", $descr="Allows employees to view and manage information regarding the veterinarians, the clients, and their pets.", $tags="Container", $link="")
      }

    }

    Deployment_Node(Live.AmazonWebServices.USEast1.AmazonRDS, "Amazon RDS", $type="", $descr="", $tags="Element", $link="") {
      Deployment_Node(Live.AmazonWebServices.USEast1.AmazonRDS.Oracle11g, "Oracle 11g", $type="", $descr="", $tags="Oracle", $link="") {
        ContainerDb(Live.AmazonWebServices.USEast1.AmazonRDS.Oracle11g.Database_1, "Database", $techn="Relational database schema", $descr="Stores information regarding the veterinarians, the clients, and their pets.", $tags="Container,Database", $link="")
      }

    }

  }

}

Rel(Live.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2.WebApplication_1, Live.AmazonWebServices.USEast1.AmazonRDS.Oracle11g.Database_1, "Reads from and writes to", $techn="MySQL Protocol/SSL", $tags="Relationship", $link="")
WithoutPropertyHeader()
AddProperty("port","443")
Rel(Live.AmazonWebServices.USEast1.Route53, Live.AmazonWebServices.USEast1.ElasticLoadBalancer, "Forwards requests to", $techn="HTTPS", $tags="Relationship", $link="")
Rel(Live.AmazonWebServices.USEast1.ElasticLoadBalancer, Live.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2.WebApplication_1, "Forwards requests to", $techn="HTTPS", $tags="Relationship", $link="")

hide stereotypes
@enduml
